# Generated by Django 4.2.1 on 2023-07-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_return_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelorder',
            name='cancel_reason',
            field=models.CharField(choices=[('Wrong Size', 'Wrong Size'), ('Other reasons', 'Other reasons')], max_length=100),
        ),
    ]
